env:
  params:
    render_mode: rgb_array

model:
  kernel_sizes: [8, 4, 1]
  strides: [4, 2, 1]
  paddings: [0, 0, 0]
  out_channels: [32, 64, 64]
  conv_activations: [ReLU, ReLU, ReLU]
  poolings: [null, null, null]
  hidden_sizes: [512]
  hidden_activations: [ReLU]
  output_activation: null

train:
  base_dir: "runs"
  num_episodes: 1000
  gamma: 0.99
  epsilon_max: 1.0
  epsilon_min: 0.001
  epsilon_decay: 0.999
  learning_rate: 0.0001
  memory_size: 10000
  batch_size: 32
  target_network: True
  target_update_freq: 25